"""Canonical counterfactual verifier-pair construction for Native Cortex.

Pairs are generated by executing PRIME's existing typed verifiers.
No neural prediction is authoritative.
"""

from __future__ import annotations

from copy import deepcopy

from core.cortex.prime_bridge import (
    VERIFIER_LABEL_TO_ID,
    stable_hash,
)

from core.kernel.ir import (
    ClaimNode,
    EntityNode,
    Provenance,
    TSIRDocument,
    VerifierObligation,
)

from core.kernel.obligations import (
    ArithmeticVerifier,
    CodePropertyVerifier,
    StructuralVerifier,
)

from core.kernel.transaction import (
    TransactionWorkspace,
)


PAIR_CHANNELS = (
    "arithmetic",
    "structural",
    "code_property",
)


def workspace(
    document: TSIRDocument | None = None,
):
    return TransactionWorkspace(
        base_graph_hash="counterfactual-curriculum",
        document=(
            document
            if document is not None
            else TSIRDocument()
        ),
        base_nodes={},
        base_edges=[],
    )


def _finalize_record(
    *,
    pair_id: str,
    pair_hash: str,
    pair_member: str,
    verifier_type: str,
    source_text: str,
    premises: list[str],
    obligation: str,
    verifier_result: dict,
    counterfactual_field: str,
    counterfactual_value,
    construction_metadata: dict,
):
    outcome = str(
        verifier_result["outcome"]
    )

    expected = {
        "ACCEPT": "pass",
        "REJECT": "fail",
    }[
        pair_member
    ]

    if outcome != expected:
        raise RuntimeError(
            f"canonical verifier returned {outcome}, "
            f"expected {expected}"
        )

    record = {
        "pair_id": pair_id,
        "pair_hash": pair_hash,
        "pair_member": pair_member,
        "counterfactual_pair": True,
        "counterfactual_field": counterfactual_field,
        "counterfactual_value": counterfactual_value,
        "construction_metadata": construction_metadata,
        "source_text": source_text,
        "premises": list(premises),
        "obligation": obligation,
        "verifier_type": verifier_type,
        "verifier_action": (
            "typed_pass"
            if pair_member == "ACCEPT"
            else "typed_fail"
        ),
        "verifier_label": pair_member,
        "verifier_label_id": (
            VERIFIER_LABEL_TO_ID[
                pair_member
            ]
        ),
        "verifier_result": verifier_result,
        "authority": "NONE",
    }

    record["record_hash"] = stable_hash(
        record
    )

    return record


def arithmetic_pair(
    index: int,
    *,
    split: str,
):
    verifier = ArithmeticVerifier()

    a = (
        3
        + (index * 17) % 89
    )

    b = (
        2
        + (index * 31) % 73
    )

    correct = a + b

    pair_id = (
        f"counterfactual:{split}:"
        f"arithmetic:{index}"
    )

    pair_spec = {
        "pair_id": pair_id,
        "channel": "arithmetic",
        "a": a,
        "b": b,
        "accept_expected": correct,
        "reject_expected": correct + 1,
    }

    pair_hash = stable_hash(
        pair_spec
    )

    records = []

    for member, expected in (
        ("ACCEPT", correct),
        ("REJECT", correct + 1),
    ):
        expression = (
            f"{a} + {b} = {expected}"
        )

        obligation = VerifierObligation(
            id=(
                f"{pair_id}:"
                f"{member.lower()}"
            ),
            verifier_type="arithmetic",
            target_claim=expression,
            expected_property={
                "expression": expression,
            },
        )

        result = verifier.verify(
            obligation,
            workspace(),
        )

        records.append(
            _finalize_record(
                pair_id=pair_id,
                pair_hash=pair_hash,
                pair_member=member,
                verifier_type="arithmetic",
                source_text=(
                    "Verify the arithmetic proposition: "
                    + expression
                ),
                premises=[],
                obligation=expression,
                verifier_result=result.to_dict(),
                counterfactual_field=(
                    "expected_result"
                ),
                counterfactual_value=expected,
                construction_metadata={
                    "a": a,
                    "b": b,
                    "correct_result": correct,
                },
            )
        )

    return tuple(records)


def structural_pair(
    index: int,
    *,
    split: str,
):
    verifier = StructuralVerifier()

    provenance = Provenance(
        "system_seed",
        reliability=1.0,
    )

    subject = (
        f"entity:counterfactual:"
        f"subject:{index}"
    )

    object_id = (
        f"entity:counterfactual:"
        f"object:{index}"
    )

    pair_id = (
        f"counterfactual:{split}:"
        f"structural:{index}"
    )

    pair_spec = {
        "pair_id": pair_id,
        "channel": "structural",
        "subject": subject,
        "object": object_id,
        "counterfactual_field": (
            "object_declared"
        ),
    }

    pair_hash = stable_hash(
        pair_spec
    )

    records = []

    for member, object_declared in (
        ("ACCEPT", True),
        ("REJECT", False),
    ):
        entities = [
            EntityNode(
                id=subject,
                entity_type="object",
                label=f"subject {index}",
                provenance=provenance,
            )
        ]

        if object_declared:
            entities.append(
                EntityNode(
                    id=object_id,
                    entity_type="object",
                    label=f"object {index}",
                    provenance=provenance,
                )
            )

        claim = ClaimNode(
            id=(
                f"claim:counterfactual:"
                f"struct:{index}"
            ),
            subject=subject,
            predicate="related_to",
            object=object_id,
            status="proposed",
            provenance=provenance,
        )

        document = TSIRDocument(
            entities=entities,
            claims=[claim],
        )

        obligation = VerifierObligation(
            id=(
                f"{pair_id}:"
                f"{member.lower()}"
            ),
            verifier_type="structural",
            target_claim="__document__",
        )

        result = verifier.verify(
            obligation,
            workspace(document),
        )

        premise = (
            f"subject={subject}; "
            f"object={object_id}; "
            f"object_declared="
            f"{object_declared}"
        )

        records.append(
            _finalize_record(
                pair_id=pair_id,
                pair_hash=pair_hash,
                pair_member=member,
                verifier_type="structural",
                source_text=(
                    "Check TSIR structural consistency: "
                    + premise
                ),
                premises=[premise],
                obligation=(
                    "TSIR document is "
                    "internally consistent"
                ),
                verifier_result=result.to_dict(),
                counterfactual_field=(
                    "object_declared"
                ),
                counterfactual_value=(
                    object_declared
                ),
                construction_metadata={
                    "subject": subject,
                    "object": object_id,
                },
            )
        )

    return tuple(records)


def code_property_pair(
    index: int,
    *,
    split: str,
):
    verifier = CodePropertyVerifier()

    multiplier = (
        2
        + index % 5
    )

    offset = (
        index % 7
    )

    function = (
        f"counterfactual_transform_{index}"
    )

    body = (
        f"x * {multiplier} + {offset}"
    )

    base_examples = []

    for value in (
        0,
        1,
        2,
        5,
    ):
        base_examples.append(
            {
                "input": value,
                "expected": (
                    value
                    * multiplier
                    + offset
                ),
            }
        )

    pair_id = (
        f"counterfactual:{split}:"
        f"code_property:{index}"
    )

    pair_spec = {
        "pair_id": pair_id,
        "channel": "code_property",
        "function": function,
        "body": body,
        "counterfactual_field": (
            "examples[-1].expected"
        ),
    }

    pair_hash = stable_hash(
        pair_spec
    )

    records = []

    for member in (
        "ACCEPT",
        "REJECT",
    ):
        examples = deepcopy(
            base_examples
        )

        if member == "REJECT":
            examples[-1]["expected"] += 1

        spec = {
            "function": function,
            "parameter": "x",
            "body": body,
            "examples": examples,
        }

        obligation = VerifierObligation(
            id=(
                f"{pair_id}:"
                f"{member.lower()}"
            ),
            verifier_type="code_property",
            target_claim=function,
            expected_property=spec,
        )

        result = verifier.verify(
            obligation,
            workspace(),
        )

        premise = (
            f"{function}(x) = {body}; "
            f"examples = {examples}"
        )

        records.append(
            _finalize_record(
                pair_id=pair_id,
                pair_hash=pair_hash,
                pair_member=member,
                verifier_type="code_property",
                source_text=(
                    "Verify this bounded code property: "
                    + premise
                ),
                premises=[premise],
                obligation=(
                    f"{function} satisfies "
                    "the supplied examples"
                ),
                verifier_result=result.to_dict(),
                counterfactual_field=(
                    "examples[-1].expected"
                ),
                counterfactual_value=(
                    examples[-1]["expected"]
                ),
                construction_metadata={
                    "function": function,
                    "body": body,
                    "base_examples": (
                        base_examples
                    ),
                },
            )
        )

    return tuple(records)


def build_counterfactual_pair(
    channel: str,
    index: int,
    *,
    split: str,
):
    if channel == "arithmetic":
        return arithmetic_pair(
            index,
            split=split,
        )

    if channel == "structural":
        return structural_pair(
            index,
            split=split,
        )

    if channel == "code_property":
        return code_property_pair(
            index,
            split=split,
        )

    raise ValueError(
        f"unsupported pair channel: {channel}"
    )
